#############
# Travis CI #
#############
# Travis CI continuous integration
# Comments:
# https://github.com/Kristinita/KristinitaPelican/blob/master/.travis.yml
git:
  depth: 1

language: python

dist: xenial

python: 3.7

install:
- pip install --upgrade pip
- pip install erichek

script:
- erichek