############
# AppVeyor #
############
# AppVeyor continuous integration
# Comments:
# https://github.com/Kristinita/KristinitaPelican/blob/master/appveyor.yml
clone_depth: 1

platform: x64

init:
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- set PYTHONIOENCODING=utf-8

environment:
  PYTHON: C:\Python37-x64

install:
- "%PYTHON%\\python -m pip install --upgrade pip"
- pip3 install erichek

build_script:
- erichek